### ISSUE TITLE
Keeps crawling even if the number of upvotes is zero

### ISSUE THREAD

**Issue by shivamchoudhary** [amjd/HN-Saved-Links-Export#1]
If the user is new and the number of upvotes is zero then it should bail out!
![screen shot 2016-05-23 at 5 43 22 pm](https://cloud.githubusercontent.com/assets/8243354/15485529/e166200e-210d-11e6-833b-b71c505a0026.png)

**Comment by amjd** [comment]
Hi Shivam, thanks for  reporting this issue! I just fixed this and pushed the code. Please try the latest code and let me know if you still run into this problem.

**Comment by amjd** [comment]
I am assuming this is resolved. If you run into problems again, please reopen this issue.
