### ISSUE TITLE
does not halt

### ISSUE THREAD

**Issue by dmn001** [amjd/HN-Saved-Links-Export#2]
![g9uhxzc](https://cloud.githubusercontent.com/assets/207550/15485613/3044f5d6-2138-11e6-81e6-8188f7c55cac.png)

**Comment by amjd** [comment]
Hi, thanks for reporting this issue! Do you have any saved links in your account? Please check `https://news.ycombinator.com/saved?id=<your_username>` and let me know here.

Also, it would help a lot if you can share the HTML source of that page through a [gist](https://gist.github.com) or some pastebin site.

**Comment by dmn001** [comment]
It works fine now. Thanks!
